childBlocks: null
field: 610e5723-d90d-4865-988f-59fc67d2dc7d # Page Parts
fieldLayouts:
  9f0cb7dc-68cc-444f-8e79-bd5b5e431bec:
    tabs:
      -
        elements:
          -
            fieldUid: 9ebc824c-bf5b-4d5e-b736-be4e71aa1ff3 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Drinks
        sortOrder: 1
group: null
handle: drinks
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Drinks
sortOrder: 4
topLevel: true
