childBlocks: null
field: 610e5723-d90d-4865-988f-59fc67d2dc7d # Page Parts
fieldLayouts:
  992808c2-3b5d-4897-bddd-284849dddd22:
    tabs:
      -
        elements:
          -
            fieldUid: 9ebc824c-bf5b-4d5e-b736-be4e71aa1ff3 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6fda7c2d-bb7b-4162-8d8b-331be2e6c83f # Cards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
group: null
handle: pricing
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Pricing
sortOrder: 2
topLevel: true
