columnSuffix: null
contentColumnType: string
fieldGroup: 798e7d9e-682f-4d1f-9b2c-0b026e7008ae # Common
handle: pageParts
instructions: ''
name: 'Page Parts'
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
  wasModified: false
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
