defaultPlacement: end
enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  34f2de1d-350d-486c-b925-c8f472300f1b: # Wirecraft
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: '{parent.slug}/{slug}'
structure:
  maxLevels: null
  uid: cc74ceaf-5b27-4130-8b81-54255ea337dc
type: structure
